using System;
using System.Collections.Generic;
using System.Threading;
using System.Threading.Tasks;
using PdfEditorApp.Core.Models;

namespace PdfEditorApp.Core.Plugins.Descriptors;

/// <summary>
/// Options provided to document exporters during export execution.
/// </summary>
public record DocumentExportOptions
{
    public string OutputPath { get; init; } = "";
    public int Dpi { get; init; } = 300;
    public bool IncludeAnnotations { get; init; } = true;
    public bool OptimizeForWeb { get; init; } = false;
    public string? Password { get; init; }
    public Dictionary<string, object> CustomParameters { get; init; } = new();
}

/// <summary>
/// Contract for a document exporter plugin that serializes a <see cref="PdfDocumentModel"/>
/// to an output format (PDF, Markdown, HTML, Plain Text, PNG/JPEG, SVG).
/// </summary>
public interface IDocumentExporter
{
    /// <summary>
    /// Unique identifier for this exporter, e.g. "frypdf.exporter.pdf" or "frypdf.exporter.markdown".
    /// </summary>
    string ExporterId { get; }

    /// <summary>
    /// User-facing display name, e.g. "PDF Document (.pdf)" or "GitHub-Flavored Markdown (.md)".
    /// </summary>
    string DisplayName { get; }

    /// <summary>
    /// Default file extension with leading dot, e.g. ".pdf", ".md", ".html".
    /// </summary>
    string DefaultExtension { get; }

    /// <summary>
    /// File filter description for OS save dialogs, e.g. "PDF Documents (*.pdf)|*.pdf".
    /// </summary>
    string FileFilterDescription { get; }

    /// <summary>
    /// Material icon name for UI representation.
    /// </summary>
    string IconKind { get; }

    /// <summary>
    /// Exports the document model and returns the generated bytes.
    /// </summary>
    Task<byte[]> ExportAsync(PdfDocumentModel document, DocumentExportOptions options, CancellationToken ct = default);
}

/// <summary>
/// Registry for discovering and managing multi-format document exporters contributed by plugins.
/// </summary>
public interface IDocumentExporterRegistry
{
    /// <summary>
    /// Registers an exporter into the system.
    /// </summary>
    IDisposable RegisterExporter(IDocumentExporter exporter);

    /// <summary>
    /// Retrieves an exporter by its unique ID.
    /// </summary>
    IDocumentExporter? GetExporter(string exporterId);

    /// <summary>
    /// Finds an exporter by output file extension (e.g. ".md" or ".html").
    /// </summary>
    IDocumentExporter? FindExporterByExtension(string extension);

    /// <summary>
    /// Gets all registered document exporters.
    /// </summary>
    IReadOnlyList<IDocumentExporter> GetAllExporters();

    /// <summary>
    /// Raised whenever an exporter is registered or unregistered.
    /// </summary>
    event Action? RegistryChanged;
}
